### ISSUE TITLE
Mac - Where is the folder to copy libspotify.framework in to?

### ISSUE THREAD

**Issue by staylor05** [pdaddyo/soundbounce#146]
I cannot figure out where the "~/Library/Framework" folder is in order to copy libspotify.framework into it. Please help!!

**Comment by Subdream** [comment]
It's on your root drive. If you are using Mavericks or later you probably have the "all my files" rubbish instead of your drives in finder. Go to finder preferences, check hard drives in options. You can now c your drive in finder. The Library folder is there on the root and the Framework folder is within it.

**Comment by pdaddyo** [comment]
Thanks @Subdream.  You can also try the terminal command on the top message here instead: #131

**Comment by staylor05** [comment]
I am running Yosemite on my Mac. I did what Subdream suggested and went into Finder Preference and clicked hardrive. When I searched for libspotify in Finder, it came up with 2...one in Microsoft Office and one in Applications in the "~/Library/Framework" folder. However, I am still unable to get my computer to find the file. Am I missing something??

**Comment by staylor05** [comment]
PS - I have no clue what a terminal command is

**Comment by Subdream** [comment]
Did you copy the libspotify.framework file to the framework folder?
