### ISSUE TITLE
Build from source instructions

### ISSUE THREAD

**Issue by ladislas** [pdaddyo/soundbounce#155]
Hi there!

First, thank you very much for what you're doing. I've been testing the Mac Beta version for a few days and it already looks great! The major drawback for the moment is huge CPU usage, but I'm sure it will fade out with time.

It would be great to also have some instruction to build from source so we can try the work in progress version and help debug.

Thanks in advance!

**Comment by pdaddyo** [comment]
The Windows version builds in Visual Studio 2012 using the .sln file, pretty simple.  The mac version isn't compiled per se, since it's a node-webkit application it's using their pre-built binary.  The source is in the src/client-node-webkit folder.  The only bit that needs compiling on OSX from source is our build of node-spotify, which I added some features too (millisecond seeking, for example).  Compile using this command in this folder https://github.com/pdaddyo/soundbounce/tree/master/src/client-node-webkit/node-spotify-master

nw-gyp rebuild --target=0.8.6

Hope that helps!

Paul

**Comment by ladislas** [comment]
Thanks a lot ! :)

I'll try that tomorrow !
