### ISSUE TITLE
Excessive CPU usage in rooms

### ISSUE THREAD

**Issue by Emerald-Phoenix** [pdaddyo/soundbounce#168]
Whenever I'm in a room and the window is active (not minimized) one of the CEF subprocesses consumes the maximum CPU time possible on one thread and writes out at fairly constant 200KB/s.

Either leaving a room (but keeping the audio playback active) or minimizing the window reduces the CPU usage to effectively zero and stop all the I/O activity.

**Comment by pdaddyo** [comment]
There is a "performance" theme planned along with the theme reworking (since this issue is in the graphics side of things, as you say minimizing the app removes almost all CPU use).  Not sure about the IO activity, I don't see that.  Also on my machine (a 4 yr old i7) it uses 10% CPU when fullscreen (1920x1080), with none of the 8 virtual cores maxed... what kind of specs (cpu, gpu) does your machine have?

**Comment by pdaddyo** [comment]
Please recheck this, should now be resolved!

**Comment by pdaddyo** [comment]
Users are reporting significant cpu drop now I've disabled the progress bar animations, closing.
