### ISSUE TITLE
Web only verion

### ISSUE THREAD

**Issue by joshhopkins** [pdaddyo/soundbounce#235]
Any progress on a web server version of Soundbound?

**Comment by andrewthecoder** [comment]
This is impossible with Spotify's current web API: 
http://stackoverflow.com/questions/24705253/play-full-spotify-track-inside-my-own-website-using-spotify-web-api?answertab=votes#tab-top

Paul has been working on a Youtube-based alternative which is already partially functional (you can anonymously listen along with an existing Soundbounce room using this URL for now, though sometimes the track played isn't quite right because youtube doesn't have everything spotify does yet: http://app.soundbounce.org/youtube?room=Travellin%27%20

**Comment by joshhopkins** [comment]
Shame about Spotify's API restrictions.

The Youtube-based alternative looks interesting – any ETA on beta testers?

Josh Hopkins | producer | engineer | 0433 166 890 | josh@therewardsroom.com
 | www.therewardsroom.com

**Comment by andrewthecoder** [comment]
We aren't really bothering with testing concept like "beta" at the moment to be honest - the entire live application is kinda one big functional beta!
As such, as soon as anyone (most likely Paul since he developed the YouTube feature so far) has developed something which actually functions, it'll probably be updated so you can try it out immediately on live - there's a button within the client at the top of rooms that opens links like the one I posted above ^^

Anyway, it's definitely something we'd like because we recognise there's plenty of people who'd like to join in but can't run desktop applications on their work PC or whatever, but there's quite a bit of work involved so nobody knows when anyone will have time to get to it. Feel free to have a crack at it yourself if you fancy learning some new skills!

**Comment by pdaddyo** [comment]
Closing this for now - we'll make it web-only if spotify deliver an API that lets us!
