### ISSUE TITLE
Sound cuts out very often on Mac

### ISSUE THREAD

**Issue by mhoydis** [pdaddyo/soundbounce#240]
Hello.  We've been trying to run Soundbounce 0.9 Beta for our office on a Mac Mini (Late 2012).  Our problem is the sound cuts out a lot.  Like, nearly every track for almost a full minute.  I recognize there's a known issue with this symptom related to the initial sync of the seed playlist, and that it's expected the symptom to disappear after a few minutes after the sync is done.  Well, for us, it persists for days.  

When we create the room, the playlist we seed it with is pretty big.  It's 781 tracks (over 51hours).  Do we think this might be related?

**Comment by gabrielfreiberg** [comment]
Sound cuts out for us too.  Several songs can play successfully, then they will start cutting out randomly.

**Comment by pdaddyo** [comment]
Yes this is frustrating for some users and a known issue with node-spotify, an alpha library that we use on OSX and linux.  It's nothing to do with playlist size.  The fix is to move to the proper CocoaLibSpotify API, but this is a huge rework and we're hoping an OSX dev takes it on (we'll accept pull requests for efforts in this area!)

**Comment by pdaddyo** [comment]
Sorry, but this is basically a wontfix until spotify release a new SDK for windows and osx, expected later in 2015
