### ISSUE TITLE
OS X - can't skip song or start a new song in the list?

### ISSUE THREAD

**Issue by maxrho** [pdaddyo/soundbounce#288]
Is this just not done yet? This is how it looks for me:

http://i.imgur.com/0CnW94U.png

Awesome application, keep it up!

<3
##

**Comment by maxrho** [comment]
Seems I don't get admin status on my own rooms? Am I missing something?

**Comment by pdaddyo** [comment]
You can vote to skip the playing song using the three-dot menu at the top of the playing track.  You can't queue another song up to play, you need votes from other users to change the order (this is by design since it's about collaboration).

You should be an admin of your own room if you created it, try typing `/listadmins` in the chat window to double check.
