### ISSUE TITLE
Do not close the application upon failed login.

### ISSUE THREAD

**Issue by brunofin** [pdaddyo/soundbounce#297]
It is very frustrating after entering the wrong credentials have the application closed and forcefully have to open it again. I believe this brings a bad user experience. I have myself given up of the application for an entire week before trying to open it again just because of this, while the solution is straightforward: Simply let the user know the credentials are wrong and take no further actions.

![ezgif-3-4f493b7c30](https://user-images.githubusercontent.com/8077237/31270452-b613af50-aa84-11e7-842f-43e08cd00bd8.gif)

**Comment by pdaddyo** [comment]
This is because of a massive memory leak in the libspotify library (that is no longer supported by spotify).  We are no longer developing v1 of soundbounce - come see v2 in development here : https://v2.soundbounce.org/ - (https://github.com/pdaddyo/soundbounce-v2) it uses proper login and Spotify Connect to control your player.
