### ISSUE TITLE
Add ability to block / report tracks, users

### ISSUE THREAD

**Issue by beveradb** [pdaddyo/soundbounce#35]
Not sure what you had in mind for this, and/or if it's already part of moderation tools which may or may not have been implemented already (I haven't tried creating my own room yet because I'm not sure if you can delete rooms yet and I don't want to clutter it up with a test room)
Anyway, something to handle the inevitable trolling which occurs in any popular community would be great.

**Comment by kcannava** [comment]
Hey, I have a current use case where a user ban or just a block/mute function would be great. Would implementing that be a possibility?

**Comment by pdaddyo** [comment]
I can ban users on the server at the moment, but there's no UI to do this on the client, even for room admins.  Is there someone particularly annoying I should know about?  If they're trolling I'm happy to ban them from the service completely.

**Comment by kcannava** [comment]
Hi Paul!

I can't confirm if he's a troll or not (i think he probably is), but he's
terribly annoying. Petri Voulsomething. I would feel bad about having him
banned from the server since that seems kind of extreme... since building
out a UI-room by room ban function is probably too high of an LOE, is
having a mute function easier/somewhere on the tracker? Muting him would
definitely suffice.

Thanks!
Katelynn
